### ISSUE TITLE
Order the parts for the drone

### ISSUE THREAD

**Issue by MaximPhoenix99** [MaximPhoenix99/Lab2019#3]
1 * Robot HATS
1 * PCA9685 PWM Driver
1 * TB6612 Motor Driver
1 * 2x18650 Battery Holder
2 * DC Gear Motor 
3 * SunFounder SF0180 Servo
1 * 120° Wide-angle USB Camera
2 * Rear Wheel
2 * Front Wheel
1 * USB Wi-Fi Adapter
1 * Ribbon (30cm)
1 * Cross Screwdriver
1 * Cross Socket Wrench
1 * M2.5/M4 Small Wrench
1 * M2/M3 Small Wrench
Several wires
Needed screws, nuts, and standoffs

**Comment by hinoeae** [comment]
still needed:
* battery / power bank
* chassis
